version: "3.8"

services:
    db:
        image: library/postgres:12-alpine
        environment:
            - POSTGRES_HOST=db
            - POSTGRES_PORT=5432
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=pelleum-dev
        ports:
            - 5432:5432