version: "3.8"

services:
    backend:                    
        build: .
        ports:
        - "8000:8000"
        container_name: pelleum-api
        env_file: 
        - env_file.env
        depends_on:
        - db   
    db:
        image: library/postgres:12-alpine
        environment:
            - POSTGRES_HOST=db
            - POSTGRES_PORT=5432
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=pelleum-dev
        ports:
            - 5432:5432
