"""Initial schema

Revision ID: 0001
Revises: 
Create Date: 2021-11-02 18:45:34.836500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("user_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "portfolios",
        sa.Column("portfolio_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("aggregated_value", sa.Float(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("portfolio_id"),
    )
    op.create_index(
        op.f("ix_portfolios_user_id"), "portfolios", ["user_id"], unique=False
    )
    op.create_table(
        "theses",
        sa.Column("thesis_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("sources", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("asset_symbol", sa.String(), nullable=False),
        sa.Column("sentiment", sa.String(), nullable=False),
        sa.Column("is_authors_current", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("thesis_id"),
        sa.UniqueConstraint("user_id", "title"),
    )
    op.create_index(
        op.f("ix_theses_asset_symbol"), "theses", ["asset_symbol"], unique=False
    )
    op.create_index(op.f("ix_theses_user_id"), "theses", ["user_id"], unique=False)
    op.create_index(op.f("ix_theses_username"), "theses", ["username"], unique=False)
    op.create_table(
        "assets",
        sa.Column("asset_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("portfolio_id", sa.BigInteger(), nullable=True),
        sa.Column("institution_id", sa.String(), nullable=True),
        sa.Column("thesis_id", sa.BigInteger(), nullable=True),
        sa.Column("asset_symbol", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("position_value", sa.Float(), nullable=True),
        sa.Column("skin_rating", sa.Float(), nullable=True),
        sa.Column("average_buy_price", sa.Float(), nullable=True),
        sa.Column("total_contribution", sa.Float(), nullable=True),
        sa.Column("is_up_to_date", sa.Boolean(), nullable=False),
        sa.Column("update_errors", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["account_connections.institutions.institution_id"],
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.portfolio_id"],
        ),
        sa.ForeignKeyConstraint(
            ["thesis_id"],
            ["theses.thesis_id"],
        ),
        sa.PrimaryKeyConstraint("asset_id"),
    )
    op.create_index(
        op.f("ix_assets_portfolio_id"), "assets", ["portfolio_id"], unique=False
    )
    op.create_index(op.f("ix_assets_thesis_id"), "assets", ["thesis_id"], unique=False)
    op.create_index(
        "ix_portfolio_id_asset_symbol_institution_id",
        "assets",
        ["portfolio_id", "asset_symbol", "institution_id"],
        unique=True,
    )
    op.create_table(
        "posts",
        sa.Column("post_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("thesis_id", sa.BigInteger(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("asset_symbol", sa.String(), nullable=True),
        sa.Column("sentiment", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["thesis_id"],
            ["theses.thesis_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("post_id"),
    )
    op.create_index(
        op.f("ix_posts_asset_symbol"), "posts", ["asset_symbol"], unique=False
    )
    op.create_index(op.f("ix_posts_thesis_id"), "posts", ["thesis_id"], unique=False)
    op.create_index(op.f("ix_posts_user_id"), "posts", ["user_id"], unique=False)
    op.create_index(op.f("ix_posts_username"), "posts", ["username"], unique=False)
    op.create_table(
        "theses_adoptions",
        sa.Column("thesis_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["thesis_id"],
            ["theses.thesis_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("thesis_id", "user_id"),
    )
    op.create_index(
        op.f("ix_theses_adoptions_thesis_id"),
        "theses_adoptions",
        ["thesis_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_theses_adoptions_user_id"),
        "theses_adoptions",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "theses_comments",
        sa.Column("comment_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("thesis_id", sa.BigInteger(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["thesis_id"],
            ["theses.thesis_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("comment_id"),
    )
    op.create_index(
        op.f("ix_theses_comments_thesis_id"),
        "theses_comments",
        ["thesis_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_theses_comments_user_id"), "theses_comments", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_theses_comments_username"),
        "theses_comments",
        ["username"],
        unique=False,
    )
    op.create_table(
        "theses_reactions",
        sa.Column("thesis_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("reaction", sa.SmallInteger(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["thesis_id"],
            ["theses.thesis_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("thesis_id", "user_id"),
    )
    op.create_index(
        op.f("ix_theses_reactions_thesis_id"),
        "theses_reactions",
        ["thesis_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_theses_reactions_user_id"),
        "theses_reactions",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "post_comments",
        sa.Column("comment_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("post_id", sa.BigInteger(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["posts.post_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("comment_id"),
    )
    op.create_index(
        op.f("ix_post_comments_post_id"), "post_comments", ["post_id"], unique=False
    )
    op.create_index(
        op.f("ix_post_comments_user_id"), "post_comments", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_post_comments_username"), "post_comments", ["username"], unique=False
    )
    op.create_table(
        "post_reactions",
        sa.Column("post_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("reaction", sa.SmallInteger(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["posts.post_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("post_id", "user_id"),
    )
    op.create_index(
        op.f("ix_post_reactions_post_id"), "post_reactions", ["post_id"], unique=False
    )
    op.create_index(
        op.f("ix_post_reactions_user_id"), "post_reactions", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_post_reactions_user_id"), table_name="post_reactions")
    op.drop_index(op.f("ix_post_reactions_post_id"), table_name="post_reactions")
    op.drop_table("post_reactions")
    op.drop_index(op.f("ix_post_comments_username"), table_name="post_comments")
    op.drop_index(op.f("ix_post_comments_user_id"), table_name="post_comments")
    op.drop_index(op.f("ix_post_comments_post_id"), table_name="post_comments")
    op.drop_table("post_comments")
    op.drop_index(op.f("ix_theses_reactions_user_id"), table_name="theses_reactions")
    op.drop_index(op.f("ix_theses_reactions_thesis_id"), table_name="theses_reactions")
    op.drop_table("theses_reactions")
    op.drop_index(op.f("ix_theses_comments_username"), table_name="theses_comments")
    op.drop_index(op.f("ix_theses_comments_user_id"), table_name="theses_comments")
    op.drop_index(op.f("ix_theses_comments_thesis_id"), table_name="theses_comments")
    op.drop_table("theses_comments")
    op.drop_index(op.f("ix_theses_adoptions_user_id"), table_name="theses_adoptions")
    op.drop_index(op.f("ix_theses_adoptions_thesis_id"), table_name="theses_adoptions")
    op.drop_table("theses_adoptions")
    op.drop_index(op.f("ix_posts_username"), table_name="posts")
    op.drop_index(op.f("ix_posts_user_id"), table_name="posts")
    op.drop_index(op.f("ix_posts_thesis_id"), table_name="posts")
    op.drop_index(op.f("ix_posts_asset_symbol"), table_name="posts")
    op.drop_table("posts")
    op.drop_index("ix_portfolio_id_asset_symbol_institution_id", table_name="assets")
    op.drop_index(op.f("ix_assets_thesis_id"), table_name="assets")
    op.drop_index(op.f("ix_assets_portfolio_id"), table_name="assets")
    op.drop_table("assets")
    op.drop_index(op.f("ix_theses_username"), table_name="theses")
    op.drop_index(op.f("ix_theses_user_id"), table_name="theses")
    op.drop_index(op.f("ix_theses_asset_symbol"), table_name="theses")
    op.drop_table("theses")
    op.drop_index(op.f("ix_portfolios_user_id"), table_name="portfolios")
    op.drop_table("portfolios")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
