"""Changed column name

Revision ID: 0002
Revises: 0001
Create Date: 2022-03-02 12:46:39.687799

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("birthdate", sa.Date(), nullable=False))
    op.drop_column("users", "birth_date")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("birth_date", sa.DATE(), autoincrement=False, nullable=False)
    )
    op.drop_column("users", "birthdate")
    # ### end Alembic commands ###
