"""comments restructuring

Revision ID: 0003
Revises: 0002
Create Date: 2021-12-26 20:28:47.680891

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_post_comments_post_id", table_name="post_comments")
    op.drop_index("ix_post_comments_user_id", table_name="post_comments")
    op.drop_index("ix_post_comments_username", table_name="post_comments")
    op.drop_table("post_comments")
    op.add_column("posts", sa.Column("is_comment_on", sa.BigInteger(), nullable=True))
    op.create_index(
        op.f("ix_posts_is_comment_on"), "posts", ["is_comment_on"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_posts_is_comment_on"), table_name="posts")
    op.drop_column("posts", "is_comment_on")
    op.create_table(
        "post_comments",
        sa.Column("comment_id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("post_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["post_id"], ["posts.post_id"], name="post_comments_post_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.user_id"], name="post_comments_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("comment_id", name="post_comments_pkey"),
    )
    op.create_index(
        "ix_post_comments_username", "post_comments", ["username"], unique=False
    )
    op.create_index(
        "ix_post_comments_user_id", "post_comments", ["user_id"], unique=False
    )
    op.create_index(
        "ix_post_comments_post_id", "post_comments", ["post_id"], unique=False
    )
    # ### end Alembic commands ###
