"""added stripe_subscription_id column

Revision ID: 0003
Revises: 0002
Create Date: 2022-02-27 17:21:12.032216

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscriptions",
        sa.Column("stripe_subscription_id", sa.String(), nullable=False),
    )
    op.create_unique_constraint(None, "subscriptions", ["stripe_subscription_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "subscriptions", type_="unique")
    op.drop_column("subscriptions", "stripe_subscription_id")
    # ### end Alembic commands ###
