"""made stripe_sub_id an index

Revision ID: 0004
Revises: 0003
Create Date: 2022-02-27 19:52:34.101401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('subscriptions_stripe_customer_id_key', 'subscriptions', type_='unique')
    op.drop_constraint('subscriptions_stripe_subscription_id_key', 'subscriptions', type_='unique')
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.create_unique_constraint('subscriptions_stripe_subscription_id_key', 'subscriptions', ['stripe_subscription_id'])
    op.create_unique_constraint('subscriptions_stripe_customer_id_key', 'subscriptions', ['stripe_customer_id'])
    # ### end Alembic commands ###
