"""removed block list arrays

Revision ID: 0004
Revises: 0003
Create Date: 2022-03-23 20:47:30.576880

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'blocked_by_list')
    op.drop_column('users', 'block_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('block_list', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('blocked_by_list', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
