"""added thesis deletes

Revision ID: 0005
Revises: 0004
Create Date: 2022-03-30 10:51:57.606528

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0005"
down_revision = "0004"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("posts_thesis_id_fkey", "posts", type_="foreignkey")
    op.create_foreign_key(
        None, "posts", "theses", ["thesis_id"], ["thesis_id"], ondelete="cascade"
    )
    op.drop_constraint("rationales_thesis_id_fkey", "rationales", type_="foreignkey")
    op.create_foreign_key(
        None, "rationales", "theses", ["thesis_id"], ["thesis_id"], ondelete="cascade"
    )
    op.drop_constraint(
        "theses_reactions_thesis_id_fkey", "theses_reactions", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "theses_reactions",
        "theses",
        ["thesis_id"],
        ["thesis_id"],
        ondelete="cascade",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "theses_reactions", type_="foreignkey")
    op.create_foreign_key(
        "theses_reactions_thesis_id_fkey",
        "theses_reactions",
        "theses",
        ["thesis_id"],
        ["thesis_id"],
    )
    op.drop_constraint(None, "rationales", type_="foreignkey")
    op.create_foreign_key(
        "rationales_thesis_id_fkey",
        "rationales",
        "theses",
        ["thesis_id"],
        ["thesis_id"],
    )
    op.drop_constraint(None, "posts", type_="foreignkey")
    op.create_foreign_key(
        "posts_thesis_id_fkey", "posts", "theses", ["thesis_id"], ["thesis_id"]
    )
    # ### end Alembic commands ###
