"""Added assets table back in.

Revision ID: 0006
Revises: 0005
Create Date: 2022-01-08 20:19:36.927761

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0006"
down_revision = "0005"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("asset_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("institution_id", sa.String(), nullable=True),
        sa.Column("thesis_id", sa.BigInteger(), nullable=True),
        sa.Column("asset_symbol", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("position_value", sa.Float(), nullable=True),
        sa.Column("skin_rating", sa.Float(), nullable=True),
        sa.Column("average_buy_price", sa.Float(), nullable=True),
        sa.Column("total_contribution", sa.Float(), nullable=True),
        sa.Column("is_up_to_date", sa.Boolean(), nullable=False),
        sa.Column("update_errors", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["account_connections.institutions.institution_id"],
        ),
        sa.ForeignKeyConstraint(
            ["thesis_id"],
            ["theses.thesis_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("asset_id"),
    )
    op.create_index(op.f("ix_assets_thesis_id"), "assets", ["thesis_id"], unique=False)
    op.create_index(op.f("ix_assets_user_id"), "assets", ["user_id"], unique=False)
    op.create_index(
        "ix_user_id_asset_symbol_institution_id",
        "assets",
        ["user_id", "asset_symbol", "institution_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_id_asset_symbol_institution_id", table_name="assets")
    op.drop_index(op.f("ix_assets_user_id"), table_name="assets")
    op.drop_index(op.f("ix_assets_thesis_id"), table_name="assets")
    op.drop_table("assets")
    # ### end Alembic commands ###
