"""added cascade delete

Revision ID: 0007
Revises: 0006
Create Date: 2022-04-15 18:35:44.428334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0007'
down_revision = '0006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('events_affected_thesis_id_fkey', 'events', type_='foreignkey')
    op.drop_constraint('events_affected_post_id_fkey', 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'posts', ['affected_post_id'], ['post_id'], ondelete='cascade')
    op.create_foreign_key(None, 'events', 'theses', ['affected_thesis_id'], ['thesis_id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key('events_affected_post_id_fkey', 'events', 'posts', ['affected_post_id'], ['post_id'])
    op.create_foreign_key('events_affected_thesis_id_fkey', 'events', 'theses', ['affected_thesis_id'], ['thesis_id'])
    # ### end Alembic commands ###
