"""Added rationales table

Revision ID: 0007
Revises: 0006
Create Date: 2022-01-11 00:00:14.094633

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0007"
down_revision = "0006"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rationales",
        sa.Column("rationale_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("thesis_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["thesis_id"],
            ["theses.thesis_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("rationale_id"),
        sa.UniqueConstraint("thesis_id", "user_id"),
    )
    op.create_index(
        op.f("ix_rationales_thesis_id"), "rationales", ["thesis_id"], unique=False
    )
    op.create_index(
        op.f("ix_rationales_user_id"), "rationales", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rationales_user_id"), table_name="rationales")
    op.drop_index(op.f("ix_rationales_thesis_id"), table_name="rationales")
    op.drop_table("rationales")
    # ### end Alembic commands ###
