"""Removed thesis_adoption table

Revision ID: 0008
Revises: 0007
Create Date: 2022-01-12 21:23:41.423314

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0008"
down_revision = "0007"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_theses_adoptions_thesis_id", table_name="theses_adoptions")
    op.drop_index("ix_theses_adoptions_user_id", table_name="theses_adoptions")
    op.drop_table("theses_adoptions")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "theses_adoptions",
        sa.Column("thesis_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("is_current", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["thesis_id"], ["theses.thesis_id"], name="theses_adoptions_thesis_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.user_id"], name="theses_adoptions_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("thesis_id", "user_id", name="theses_adoptions_pkey"),
    )
    op.create_index(
        "ix_theses_adoptions_user_id", "theses_adoptions", ["user_id"], unique=False
    )
    op.create_index(
        "ix_theses_adoptions_thesis_id", "theses_adoptions", ["thesis_id"], unique=False
    )
    # ### end Alembic commands ###
