"""added cascade delete for comments

Revision ID: 0008
Revises: 0007
Create Date: 2022-04-15 18:42:07.877814

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0008"
down_revision = "0007"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("events_comment_id_fkey", "events", type_="foreignkey")
    op.create_foreign_key(
        None, "events", "posts", ["comment_id"], ["post_id"], ondelete="cascade"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "events", type_="foreignkey")
    op.create_foreign_key(
        "events_comment_id_fkey", "events", "posts", ["comment_id"], ["post_id"]
    )
    # ### end Alembic commands ###
