"""Added on_delete

Revision ID: 0009
Revises: 0008
Create Date: 2022-02-03 23:34:32.971821

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0009"
down_revision = "0008"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "post_reactions_post_id_fkey", "post_reactions", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "post_reactions", "posts", ["post_id"], ["post_id"], ondelete="cascade"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "post_reactions", type_="foreignkey")
    op.create_foreign_key(
        "post_reactions_post_id_fkey",
        "post_reactions",
        "posts",
        ["post_id"],
        ["post_id"],
    )
    # ### end Alembic commands ###
